#
# Format:
#
# <heroku_san shorthand name>:
#   app: <Heroku app name>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production:
  app: firewatch
  config:
    BUNDLE_WITHOUT: "development:test"

staging:
  app: firewatch-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"

demo:
  app: firewatch-demo
  config: *default

